configfile:
  firstArrivalTime: [["Q1", 2.0]]
  quantityRandomNumbers: 100000
  seed: 12345
  queueList:
    - name: "Q1"
      servers: 1
      minArrival: 2.0
      maxArrival: 4.0
      minService: 1.0
      maxService: 2.0
      network:
        - target: "Q2"
          probability: 0.8
        - target: "Q3"
          probability: 0.2
    - name: "Q2"
      servers: 2
      capacity: 5
      minService: 4.0
      maxService: 8.0
      network:
        - target: "Q1"
          probability: 0.3
        - target: "Q2"
          probability: 0.5
    - name: "Q3"
      servers: 2
      capacity: 10
      minService: 5.0
      maxService: 15.0
      network:
        - target: "Q3"
          probability: 0.7
